//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors_Movie
    {
        public int CMID { get; set; }
        public int MID { get; set; }
        public int AID { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
